name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Build
        run: go build -v ./...

      - name: Run unit tests and generate coverage
        run: go test -v -coverprofile cover.out ./... -tags unit_test

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cover.out

      - name: Run integration tests and generate coverage
        run: go test -v -coverprofile cover.out ./... -tags integration

      - name: Upload integration coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: integration-coverage-report
          path: cover.out

  visualize-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage-report

      - name: Generate and upload coverage badge
        run: |
          go get -u github.com/jpoles1/gopherbadger
          gopherbadger -md="README.md"

      - name: Upload README.md as artifact
        uses: actions/upload-artifact@v2
        with:
          name: readme
          path: README.md
