name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build
        run: go build -v ./...

      - name: unit-test
        run: go test -v -coverprofile cover.out  ./... -tags unit_test

      - name: total-unit-test-coverage
        run:  go tool cover -func=cover.out

      - name: integration-test
        run: go test -v -coverprofile cover.out  ./... -tags integration
